name: drought
channels:
  - conda-forge
  - base
  - R
dependencies:
  - r-base=4.3.3
  - r-tidyverse=2.0.0
  - wget-1.20.3

  # mamba env create -f environment.yml
  # conda activate drought
  # conda deactivate
  # conda env list

  # R
  # .libPaths()
  # library(tidyverse)